CREATE TABLE {tableName} (
    SEQ_NUM varcha2r(20) DEFAULT NULL,
    MESSAGEID varchar2(128) DEFAULT NULL,
    R_DATE varchar2(24) DEFAULT NULL,
    ORGADDR varchar2(32) DEFAULT NULL,
    DSTADDR varchar2(32) DEFAULT NULL,
    CALLBACK varchar2(32) DEFAULT NULL,
    TEXTTYPE char(1) DEFAULT NULL,
    CONTENT_TYPE varchar2(4) DEFAULT NULL,
    SUBJECT varchar2(60) DEFAULT NULL,
    ATTACH_FILE_NUM varchar2(2) DEFAULT NULL,
    MESSAGE varchar2(2000) DEFAULT NULL,
    PRIMARY KEY (SEQ_NUM)
);

CREATE INDEX idx_mms_rDate ON {tableName}(R_DATE);