#######################################################################
#
# SMS CPA 설정파일
#
#######################################################################

#홈 디렉토리	
CPA_HOME = ./

#로그 디렉토리	
CPA_LOGDIR = ./LOG

#로그 레벨 (1 ~ 5)
CPA_LOGLEVEL = 3

#######################################################################
# 서버 연동 설정
#######################################################################
#서버IP
SERVER_IP =

#서버 포트번호	
SERVER_PORT = 51100

#서버 계정 ID	
SERVER_ID =

#서버 계정 PASSWORD	
SERVER_PASSWD =

#LINECHECK TIMEOUT 시간(30 ~ 300 초)
LINECHK_TIMEOUT = 60

#######################################################################
# 데이터베이스 설정
#######################################################################
#DB종류 (MYSQL, MSSQL, ORACLE)
DB_TYPE	=

#DB접속 IP
DB_IP =

#DB접속 포트번호
DB_PORT =

#DB접속 ID	
DB_USERNAME =

#DB접속 PASSWORD	
DB_PASSWD =

#DB접속 이름(ORACLE SID)	
DB_NAME	=

#DB Charset(EUCKR, UTF8)
DB_CHARSET = EUCKR

#작업 테이블 이름
DB_TABLE = kct_sms_rcv

#DB접속 체크 주기(sec)
DB_CONN_CHECK = 10
